### ISSUE TITLE
oa.data is missing

### ISSUE THREAD

**Issue by leix28** [lethaiq/shield-defend-adversarial-texts#1]
Hi @lethaiq ,

I was trying to run this library. It seems like the `OpenAttack/OpenAttack/data` is not uploaded.

**Comment by lethaiq** [comment]
hey @leix28 ,

Sorry for the late reply.
the data folder should be automatically created by OpenAttack framework. It is used to store all the artifacts to be used by attackers.

Have you tried following
```
cd OpenAttack
python -m pip install -e .
```
and run again?

If you still face errors please let me know!

**Comment by lethaiq** [comment]
@leix28 
I fixed this. Sorry for being late.

**Comment by lethaiq** [comment]
hi,

Can you try:

Install the OpenAttack according to the installation using pip -e. Then,
OpenAttack will automatically creates the data folder and download all the
artifacts there.

Please let me know if you still face errors.
